# Generated by Django 5.0.7 on 2024-07-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teneastapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='question',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
